# Generated by Django 5.0.3 on 2024-03-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_remove_user_is_staff_doctors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
