# Generated by Django 5.0.3 on 2024-03-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
